
name: Test restful-booker API

on:
  push:
    branches: [ temp ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      
    - name: Navigate to project directory
      run: cd restful-booker-api-at/restful-booker

    - name: Initialize and update submodules
      run: git submodule update --init --recursive
      
    - name: Install dependencies
      run: npm install

    - name: Start the server
      run: npm start

    - name: Run Newman tests
      uses: matt-ball/newman-action@master
      with:
        collection: Restful Booker API.postman_collection.json
        environment: Restful booker - Local.postman_environment.json
